### ISSUE TITLE
Test with xubuntu 16.04

### ISSUE THREAD

**Issue by serpico** [lsrdg/Tatoeba-query#1]
with python 3.5.1-3 installed

`git clone https://github.com/lsrdg/tatoeba-karini`

`arno@arno-1005HA:~$ python tatoeba-karini -b eng jpn breath
/usr/bin/python: can't find '__main__' module in 'tatoeba-karini'`

and

`arno@arno-1005HA:~$ python tatoeba-karini -i eng jpn breath
/usr/bin/python: can't find '__main__' module in 'tatoeba-karini'`

**Comment by lsrdg** [comment]
Hi, @serpico, thanks for creating the issue!

Looking at your code example, it looks like you cloned the repository to your home folder. From your home directory (`arno@arno-1005HA:~$`) you can:

1 - tell python where the script is: 

 ` ~$ python tatoeba-karini/tatoeba-karini.py -b eng jpn breath`

2 - change to the repository you cloned (with the `cd` command) and then tell python where the script is:
```
$ cd tatoeba-karini/
$ python tatoeba-karini.py -b eng jpn breath
```

3 - Create an alias (a shortcut) to the Tatoeba-karini script:

In my `~/.bashrc` file, I have something like: 
```
# tatoeba-karini
alias tatoeba-karini='python ~/git/tatoeba-karini/tatoeba-karini.py
```
Now, I can just open a terminal and type: `tatoeba-karini -b eng jpn breath` directly.

I am not a xubuntu user, but after searching a bit I found a bit more elegant way of creating alias here: https://askubuntu.com/questions/1414/how-to-create-a-permanent-alias

Please, do not hesitate if you need any help.
Now that I know that someone other than me is trying it out, I'll give it more attention. (:

**Comment by serpico** [comment]
Thanks for looking into it! :)

`arno@arno-1005HA:~$ python tatoeba-karini/tatoeba-karini.py -b eng jpn breath
Traceback (most recent call last):
  File "tatoeba-karini/tatoeba-karini.py", line 1, in <module>
    import webbrowser, argparse, sys, os, csv, requests, bs4, lxml, tarfile
ImportError: No module named requests`

`arno@arno-1005HA:~$ cd tatoeba-karini/
arno@arno-1005HA:~/tatoeba-karini$ python tatoeba-karini.py -b eng jpn breath
Traceback (most recent call last):
  File "tatoeba-karini.py", line 1, in <module>
    import webbrowser, argparse, sys, os, csv, requests, bs4, lxml, tarfile
ImportError: No module named requests
arno@arno-1005HA:~/tatoeba-karini$ `

I tinkered the alias in `.bash_aliases` adjusted the path and added the missing `'` then : 

`arno@arno-1005HA:~$ tatoeba-karini -b eng jpn breath
Traceback (most recent call last):
  File "/home/arno/tatoeba-karini/tatoeba-karini.py", line 1, in <module>
    import webbrowser, argparse, sys, os, csv, requests, bs4, lxml, tarfile
ImportError: No module named requests
arno@arno-1005HA:~$ `

**Comment by lsrdg** [comment]
You're welcome and thanks for caring! (:

> ImportError: No module named requests

The `requests` module is not a built-in module and it needs to be installed a part with `pip` (tool for installing python packages). Please, take a look at this answer: https://askubuntu.com/questions/351976/how-to-install-requests-module-for-python-3-2-by-using-pip-install

However, the answer includes a `$ sudo apt-get install python3-setuptools` which you probably don't need in this case.
This link seems to have a better explanation (and an introduction to pip): https://www.rosehosting.com/blog/how-to-install-pip-on-ubuntu-16-04/ , but take a look at the discussion on the comments, because there are two things you need to consider here:

1) you need pip (and requests) for python**3**, not python2.

2) You probably don't want to mix your (user) packages (like `requests`) with the (python) packages used by your system, so in instead of something like:

```
$ sudo apt-get install python-pip
```
Use the `--user` option to install the package for your user, and not for the whole system. Probably something like:

```
$ sudo pip install --user python-pip
```

Sorry if all of this (pip, python2/3, etc) is just plain old news for you, and I am just being repetitive... but I couldn't find a better way to describe it.

> I tinkered the alias in `.bash_aliases` adjusted the path and added the missing `'` then :

Oops! Nice catch!

**Comment by lsrdg** [comment]
Hi @serpico , any thing new on this?
closing the issue now, but feel free to ask or give any feedback on how it could be improved.

Thanks again
